# Generated by Django 4.1.7 on 2023-06-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyershop', '0008_supportlink_link_support_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportLink',
        ),
        migrations.RemoveField(
            model_name='link',
            name='support_link',
        ),
    ]
