# Generated by Django 4.1.7 on 2023-06-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyershop', '0009_delete_supportlink_remove_link_support_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название/Описание')),
                ('link', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('media_icon', models.CharField(choices=[('instagram', 'Инстаграм'), ('telegram', 'Телеграм'), ('whatsapp', 'Ватсап'), ('tiktok', 'Тик-ток')], max_length=255)),
                ('cover', models.ImageField(upload_to='media/images', verbose_name='Фото из соцсети')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
